"""TradeBooths model added

Revision ID: 2afcda682491
Revises: a5d53f17c76b
Create Date: 2025-03-07 15:08:48.088952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afcda682491'
down_revision = 'a5d53f17c76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_booth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_pdf_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_pdf_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_pdf_file_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_docx_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_docx_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_docx_file_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('document_file_id')
        batch_op.drop_column('document_url')
        batch_op.drop_column('document_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_booth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('document_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('document_file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('document_docx_file_id')
        batch_op.drop_column('document_docx_url')
        batch_op.drop_column('document_docx_filename')
        batch_op.drop_column('document_pdf_file_id')
        batch_op.drop_column('document_pdf_url')
        batch_op.drop_column('document_pdf_filename')

    # ### end Alembic commands ###
