"""set the time fields

Revision ID: 786fe2015f94
Revises: f7fa84c38a2a
Create Date: 2025-03-10 11:36:28.117912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786fe2015f94'
down_revision = 'f7fa84c38a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_booth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_pdf_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_docx_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_booth', schema=None) as batch_op:
        batch_op.drop_column('document_docx_filename')
        batch_op.drop_column('document_pdf_filename')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
