"""set the time fields

Revision ID: 898cc2f55771
Revises: c0090ed41db4
Create Date: 2025-03-10 12:18:51.661739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898cc2f55771'
down_revision = 'c0090ed41db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
