"""new filed_id added

Revision ID: 8e26dd482b78
Revises: 9cfb347a946e
Create Date: 2025-03-07 10:00:13.075938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e26dd482b78'
down_revision = '9cfb347a946e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
